### ISSUE TITLE
scale = log in GaussianMixture1DOp

### ISSUE THREAD

**Issue by kkiwimagi** [bpteague/cytoflow#111]
I get the following error in a 1DOp mixture model when I use a log scale. However this works just fine if I use logical?
![image](https://cloud.githubusercontent.com/assets/27301942/26119326/d81fe254-3a3a-11e7-9244-68ff435100f0.png)
![image](https://cloud.githubusercontent.com/assets/27301942/26119355/ec1f70da-3a3a-11e7-8623-f536c60ee240.png)

(Aside: The somewhat different distribution for my transfected population is likely coming from the observation that my circuits are stably integrated.)

**Comment by bpteague** [comment]
Hi Kathrine - are you using v0.5?  If not, make sure you've upgraded.

I've run into this before; I seem to recall it's an issue with the version of one of the dependent packages. Poke me on Monday and we'll get this figured out.  (You're not the first person to report this.)

**Comment by kkiwimagi** [comment]
Hi Brian,
Upgrading worked. Thank you,
Katherine
