### ISSUE TITLE
gm = flow.GaussianMixture1DOp

### ISSUE THREAD

**Issue by kkiwimag** [bpteague/cytoflow#112]
`gm = flow.GaussianMixture1DOp(name = "Transfected_GM",
                              channel = "Pacific Blue-A",
                              posteriors = True,
                              num_components = 2,
                              scale='log')
gm.estimate(ex_beads,subset = "Morpho1 == True and Morpho2 == True")
#gm.default_view().plot(ex_beads)
ex_gm = gm.apply(ex_beads)

ex_gm.add_condition("Transfected", 
                    "bool",
                    ((ex_gm["Transfected_GM"] == "Transfected_GM_2") & 
                     (ex_gm["Transfected_GM_Posterior"] > 0.95)))`

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-f9665326b892> in <module>()
      6 gm.estimate(ex_beads,subset = "Morpho1 == True and Morpho2 == True")
      7 #gm.default_view().plot(ex_beads)
----> 8 ex_gm = gm.apply(ex_beads)
      9 
     10 ex_gm.add_condition("Transfected", 

/Users/katherine/cytoflow/cytoflow/operations/gaussian_1d.pyc in apply(self, experiment)
    410                         g = group
    411 
--> 412                     mean_stat.loc[g] = self._scale.inverse(gmm.means_[c][0])
    413                     stdev_stat.loc[g] = self._scale.inverse(np.sqrt(gmm.covariances_[c][0]))[0]
    414                     interval_stat.loc[g] = (self._scale.inverse(gmm.means_[c][0] - np.sqrt(gmm.covariances_[c][0][0])),

/anaconda/lib/python2.7/site-packages/pandas/core/indexing.pyc in __setitem__(self, key, value)
    139             key = com._apply_if_callable(key, self.obj)
    140         indexer = self._get_setitem_indexer(key)
--> 141         self._setitem_with_indexer(indexer, value)
    142 
    143     def _has_valid_type(self, k, axis):

/anaconda/lib/python2.7/site-packages/pandas/core/indexing.pyc in _setitem_with_indexer(self, indexer, value)
    329                 if self.ndim == 1:
    330                     index = self.obj.index
--> 331                     new_index = index.insert(len(index), indexer)
    332 
    333                     # we have a coerced indexer, e.g. a float

/anaconda/lib/python2.7/site-packages/pandas/indexes/category.pyc in insert(self, loc, item)
    566         code = self.categories.get_indexer([item])
    567         if (code == -1):
--> 568             raise TypeError("cannot insert an item into a CategoricalIndex "
    569                             "that is not already an existing category")
    570 

TypeError: cannot insert an item into a CategoricalIndex that is not already an existing category

**Comment by bpteague** [comment]
This was a bug in the `pandas` category handling.  Pretty sure this is fixed in the latest release; if not, please re-open.
