### ISSUE TITLE
Bins not disappearing (HistogramView)

### ISSUE THREAD

**Issue by kkiwimag** [bpteague/cytoflow#113]
The bins in the histogram view function are not changing when subset conditions are changed
![screenshot 2017-05-23 13 13 56](https://cloud.githubusercontent.com/assets/10065588/26366633/cf3f256c-3fb9-11e7-9862-0b4889b001b4.png)
![screenshot 2017-05-23 13 14 17](https://cloud.githubusercontent.com/assets/10065588/26366634/cf403e2a-3fb9-11e7-90b1-92681a91effd.png)

**Comment by bpteague** [comment]
Pretty sure this is fixed in v1.0.  If not, please re-open with some example data and a complete notebook so I can reproduce it.
