### ISSUE TITLE
error bars in Stats1DView

### ISSUE THREAD

**Issue by kkiwimag** [bpteague/cytoflow#114]
Having trouble getting error bars in Stats1DView to app
![screenshot 2017-05-23 13 54 55](https://cloud.githubusercontent.com/assets/10065588/26368362/6bc9f574-3fbf-11e7-9f22-4c9508f4fb4a.png)
ear.

**Comment by bpteague** [comment]
This code was updated pretty dramatically in v1.0.  Have another go and if it's still an issue, please re-open.
