### ISSUE TITLE
Installation failed: no file logicle.h

### ISSUE THREAD

**Issue by pochekailov** [bpteague/cytoflow#12]
Hi,

I'm trying to install cytoflow on Ubuntu 14.04 fully up-to-date.

"pip install cytoflow" fails with error:
cytoflow/utility/logicle_ext/FastLogicle.cpp:1:21: fatal error: logicle.h: No such file or directory

Thanks

**Comment by bpteague** [comment]
Sorry!  This got fixed in 0.3 (I think!).
