### ISSUE TITLE
install on windows machine

### ISSUE THREAD

**Issue by kkiwimagi** [bpteague/cytoflow#120]
both 
pip install cytoflow
and
conda install --file=packaging/conda-requirements.txt

are running to dependencies errors

![image](https://user-images.githubusercontent.com/27301942/27642870-0f9f7ba2-5bee-11e7-8429-e576c84b1b66.png)

![image](https://user-images.githubusercontent.com/27301942/27642760-bf473b4a-5bed-11e7-8299-8bcc16487613.png)

**Comment by kkiwimagi** [comment]
Installing the one python package found at http://aka.ms.vcpython27 fixed the issue.
pip install cytoflow was successful:)

**Comment by bpteague** [comment]
In the future, make sure you're using a fresh conda environment instead of installing into your base environment.
