### ISSUE TITLE
bin count and histogram view

### ISSUE THREAD

**Issue by kkiwimagi** [bpteague/cytoflow#121]
How do I remove bins with less than 100 points in them for the histogram view?

The script below does not appear to be working.
![screenshot 2017-06-28 15 58 41](https://user-images.githubusercontent.com/27301942/27657457-bdb02378-5c1a-11e7-913f-b2d1816d51c9.png)

Thank you for your help,
K

**Comment by bpteague** [comment]
You can pass `bin_count_name` to `BinningOp` to add a piece of metadata to the new `Experiment` containing the bin count, then filter using `HistogramOp`'s `subset` parameter.  Check out the TASBE  notebook in `docs/examples-advanced` for an example.
