### ISSUE TITLE
af and bl comp

### ISSUE THREAD

**Issue by kkiwimagi** [bpteague/cytoflow#122]
I am unsure if code below should equal 0,
`np.sum(ex_af.data["PE-Texas Red-A"]-ex_bl.data["PE-Texas Red-A"])`
when ex_af is auto florescence correction and ex_bl is bleed through correction.

In other words where is the ex_af data stored?

Thank you for your help,
Katherine

**Comment by bpteague** [comment]
I'm not sure what you're asking.  Can see if this is still an issue in v1.0?  If so, please re-open and give me a reproducible test-case (code plus data to try it out on.)
