### ISSUE TITLE
cannot build: ImportError: The 'packaging.version' package is required

### ISSUE THREAD

**Issue by tim-tx** [bpteague/cytoflow#123]
This is on a standard ArchLinux system. Trying `python2 setup.py build` produces the following:

    Traceback (most recent call last):
      File "setup.py", line 20, in <module>
        from setuptools import setup, find_packages, Extension
      File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, map
      File "/usr/lib/python2.7/site-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
        __import__('pkg_resources.extern.packaging.version')
      File "/usr/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 61, in load_module
        "distribution.".format(**locals())
    ImportError: The 'packaging.version' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

The `packaging` directory from your source tree seems to be conflicting with my system-wide installation of the python 'packaging' package (required by setuptools). If I remove the local `packaging` dir the build works (and if I try `python2 -c "import packaging.version"` from some other directory there is no error). Are the files in this directory used for anything? You referred to it as cruft in a commit. My suspicion is that this directory has nothing to do with the 'packaging' package, or if it does, the files there are misconfigured in some way.

**Comment by bpteague** [comment]
Hi @tim-tx -- you are correct, the `packaging` subfolder does not have anything to do with `setuptools.packaging`.  (It contains packaging-related resources, like PyInstaller hooks and Anaconda recipes.)

I have removed `__init__.py`, so Python should no longer think that this directory is a package.
