### ISSUE TITLE
import cytoflow: fatal: Not a git repository (or any parent up to mount point /)

### ISSUE THREAD

**Issue by tim-tx** [bpteague/cytoflow#124]
After `import cytoflow`, I see this mesage: `fatal: Not a git repository (or any parent up to mount point /)`. It's a minor annoyance, comes from [here](https://github.com/bpteague/cytoflow/blob/7922cd46c1e5a00b8debcea4f4e7827e776fb6fd/cytoflow/__init__.py#L79) I think. Note this is with the 0.5.2 tarball and after packaging, so there wouldn't be any `.git` stuff around. And in any case, I still get:

    >>> cytoflow.__version__
    '0.5.2'

**Comment by bpteague** [comment]
Hi @tim-tx -- thanks for the bug report (and sorry it's taken me a while to get to it.)  I hope you realized that the error was non-fatal, even though it said "fatal" (-:  This issue is fixed in HEAD, and will be included in the 0.9 release very soon.
