### ISSUE TITLE
enable easier data experimental information tagging

### ISSUE THREAD

**Issue by bhwein** [bpteague/cytoflow#125]
Is it possible to incorporate a nice (more than one cell) copy and paste feature into the data import to input category, number, true-false information? Even better, a .XLS or .CSV etc template important function would be even better. This would save a tremendous amount of time and potential for error.
-Ben

**Comment by bpteague** [comment]
Version 1.0 has a .CSV import function in the experiment setup dialog!  Woohoo!!
