### ISSUE TITLE
data analysis is slow upon re-opening

### ISSUE THREAD

**Issue by bhwein** [bpteague/cytoflow#126]
I know this may not be easy or possible to implement, but is it possible to not have to go through the entire analysis after re-opening the cytoflow file if there have been no changes to the data files. Its painful if the software quits out and you have to spend all the time waiting for all the processes to complete again.

**Comment by bpteague** [comment]
Unfortunately, saving all those intermediate computation results would be difficult.  On the plus side, the latest version crashes much, much less.  Try it an let me know what you think!
