### ISSUE TITLE
python setup.py egg_info fail

### ISSUE THREAD

**Issue by bhwein** [bpteague/cytoflow#134]
I get this error when installing cytoflow:

![untitled 2](https://user-images.githubusercontent.com/28678480/28584884-5235bdf6-713c-11e7-857c-b8e29c525a6b.jpeg)

**Comment by bhwein** [comment]
Oops. I think this is because I had python 3.6 rather than 2.7.

**Comment by bpteague** [comment]
Heh.  v1.0 uses python 3.4+.  And, use Anaconda!
