### ISSUE TITLE
excel/spreadsheet import

### ISSUE THREAD

**Issue by bhwein** [bpteague/cytoflow#146]
Large experiments can take an extraordinary amount of time to setup within cytoflow. It will be deeply appreciated to incorporate a faster means (e.g. .xls, .txt, .csv etc import) of annotating the samples (e.g. inducer, replicates, conditions).

**Comment by bpteague** [comment]
CSV import of experiment setup is a new feature in HEAD!  i expect to be rolling a new release this week; please give it a shot and tell me what you think!
