### ISSUE TITLE
Exporting to CSV Incomplete

### ISSUE THREAD

**Issue by jhletendre** [bpteague/cytoflow#148]
When exporting data to a .csv file using the Export... button in the 1D Statistics View tab, numbers from the 'number' category below 1.0 associated with specific data do not translate correctly. The table appears fine in the Cytoflow program, but numbers below 1.0 appear only as 0.0 in the .csv file. There are no error codes are associated with this.

**Comment by bpteague** [comment]
this should be fixed in HEAD.  if it's not fixed in version 1.0, please re-open.
