### ISSUE TITLE
Exporting to CSV Failed

### ISSUE THREAD

**Issue by jhletendre** [bpteague/cytoflow#149]
Received the following message when trying to export a .csv document using the 2D statistics view:

Error: TypeError: Level type mismatch: 1

Location: File "site-packages\pandas\indexes\multi.py", line 1594, in _partial_tup_index
Thread: MainThread

**Comment by bpteague** [comment]
this should be fixed in HEAD.  if it's not fixed in the 1.0 release (coming out this week!), please re-open.
