### ISSUE TITLE
ScatterPlotView with log scale: too many kwargs for mpl's LogScale

### ISSUE THREAD

**Issue by tim-tx** [bpteague/cytoflow#158]
See the following trace and following comments:

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-6-4f2b4f943e38> in <module>()
          1 flow.ScatterplotView(xchannel = "FSC-A",
          2                      ychannel = "SSC-A",
    ----> 3                      yscale = "log").plot(ex, alpha = 0.01)
          4 plt.xlim((0,300000));

    ~/postdoc/src/cytoflow/cytoflow/views/scatterplot.py in plot(self, experiment, **kwargs)
         99         """
        100 
    --> 101         super().plot(experiment, **kwargs)
        102 
        103     def _grid_plot(self, experiment, grid, xlim, ylim, xscale, yscale, **kwargs):

    ~/postdoc/src/cytoflow/cytoflow/views/base_views.py in plot(self, experiment, **kwargs)
        449                      ylim = ylim,
        450                      yscale = yscale,
    --> 451                      **kwargs)        
        452 
        453 class BaseNDView(BaseView):

    ~/postdoc/src/cytoflow/cytoflow/views/base_views.py in plot(self, experiment, **kwargs)
        274                                              .format(self.subset))
        275 
    --> 276         super().plot(experiment, experiment.data, **kwargs)
        277 
        278 

    ~/postdoc/src/cytoflow/cytoflow/views/base_views.py in plot(self, experiment, data, **kwargs)
        152                 ax.set_xscale(xscale.name, **xscale.mpl_params)
        153             if yscale:
    --> 154                 ax.set_yscale(yscale.name, **yscale.mpl_params)
        155 
        156         # if we are sharing x axes, make sure the x scale is the same for each

    /usr/lib/python3.6/site-packages/matplotlib/axes/_base.py in set_yscale(self, value, **kwargs)
       3344         g = self.get_shared_y_axes()
       3345         for ax in g.get_siblings(self):
    -> 3346             ax.yaxis._set_scale(value, **kwargs)
       3347             ax._update_transScale()
       3348             ax.stale = True

    /usr/lib/python3.6/site-packages/matplotlib/axis.py in _set_scale(self, value, **kwargs)
        709 
        710     def _set_scale(self, value, **kwargs):
    --> 711         self._scale = mscale.scale_factory(value, self, **kwargs)
        712         self._scale.set_default_locators_and_formatters(self)
        713 

    /usr/lib/python3.6/site-packages/matplotlib/scale.py in scale_factory(scale, axis, **kwargs)
        551         raise ValueError("Unknown scale type '%s'" % scale)
        552 
    --> 553     return _scale_mapping[scale](axis, **kwargs)
        554 scale_factory.__doc__ = dedent(scale_factory.__doc__) % \
        555     {'names': " | ".join(get_scale_names())}

    /usr/lib/python3.6/site-packages/matplotlib/scale.py in __init__(self, axis, **kwargs)
        240                               "{'basex', 'subsx', nonposx'} or "
        241                               "{'basey', 'subsy', nonposy'}.  You passed ") +
    --> 242                              "{!r}".format(kwargs))
        243 
        244         if nonpos not in ['mask', 'clip']:

    ValueError: provided too many kwargs, can only pass {'basex', 'subsx', nonposx'} or {'basey', 'subsy', nonposy'}.  You passed {'nonposx': 'mask'}

In [``utility/log_scale.py:55``](https://github.com/bpteague/cytoflow/blob/e1dbbdc4d4a920a738689362f3793e4492e11102/cytoflow/utility/log_scale.py#L55) you have:

    def _get_mpl_params(self):
        return {"nonposx" : self.mode, 
                "nonposy" : self.mode}

But in matplotlib's [``scale.py:229``](https://github.com/matplotlib/matplotlib/blob/8d60d541cfa5e3e706724167665ef8a6af4dd07e/lib/matplotlib/scale.py#L229):

        if axis.axis_name == 'x':
            base = kwargs.pop('basex', 10.0)
            subs = kwargs.pop('subsx', None)
            nonpos = kwargs.pop('nonposx', 'clip')
        else:
            base = kwargs.pop('basey', 10.0)
            subs = kwargs.pop('subsy', None)
            nonpos = kwargs.pop('nonposy', 'clip')

        if len(kwargs):
            raise ValueError(("provided too many kwargs, can only pass "
                              "{'basex', 'subsx', nonposx'} or "
                              "{'basey', 'subsy', nonposy'}.  You passed ") +
                             "{!r}".format(kwargs))

So I'm guessing what happened is that, while we're using a log scale on the y axis, both ``nonposx`` and ``nonposy`` were sent in ``kwargs``, but ``nonposx`` didn't get ``pop``'d and thus the error. I have matplotlib-2.1.1 installed on my system.

I don't know if this is an ideal solution, but editing [``views/base_views.py:150``]( https://github.com/bpteague/cytoflow/blob/e1dbbdc4d4a920a738689362f3793e4492e11102/cytoflow/views/base_views.py#L150) to be the following got me a plot:

    for ax in g.axes.flatten():
        if xscale:
            params = xscale.mpl_params
            if 'nonposy' in params:
                params.pop('nonposy')
            ax.set_xscale(xscale.name, **params) 
        if yscale:
            params = xscale.mpl_params
            if 'nonposx' in params:
                params.pop('nonposx')
            ax.set_yscale(yscale.name, **params)

**Comment by bpteague** [comment]
this was due to an API change in the new version of matplotlib.  i was stuck with 1.5.x because we were using Qt 4.x; but now we're using Qt 5 and the latest-and-greatest matplotlib, so it should be fixed in HEAD.

also -- i highly (*highly*) recommend using the pinned versions of the dependencies, either with a venv or a conda environment.  i can't guarantee that if, say, the pandas API changes, that cytoflow will keep working.
