### ISSUE TITLE
ValueError: buffer source array is read-only (from pandas, after ImportOp.apply())

### ISSUE THREAD

**Issue by tim-tx** [bpteague/cytoflow#159]
See the following trace and comments:

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-3-92f47e18eb12> in <module>()
         13                                         'Sample' : "category"},
         14                           tubes = tubes)
    ---> 15 ex = import_op.apply()

    ~/postdoc/src/cytoflow/cytoflow/operations/import_op.py in apply(self, experiment)
        317                                   util.CytoflowWarning)
        318 
    --> 319             experiment.add_events(tube_data[channels], tube.conditions)
        320 
        321         for channel in channels:

    ~/postdoc/src/cytoflow/cytoflow/experiment.py in add_events(self, data, conditions)
        486         # already
        487 
    --> 488         if( any(True for k in conditions if k not in self.conditions) or \
        489             any(True for k in self.conditions if k not in conditions) ):
        490             raise util.CytoflowError("Metadata for this tube should be {}"

    ~/postdoc/src/cytoflow/cytoflow/experiment.py in <genexpr>(.0)
        486         # already
        487 
    --> 488         if( any(True for k in conditions if k not in self.conditions) or \
        489             any(True for k in self.conditions if k not in conditions) ):
        490             raise util.CytoflowError("Metadata for this tube should be {}"

    ~/postdoc/src/cytoflow/cytoflow/experiment.py in _get_conditions(self)
        186     def _get_conditions(self):
        187         """Getter for the `conditions` property"""
    --> 188         return {x : pd.Series(self.data[x].unique()).sort_values() for x in self.data
        189                 if self.metadata[x]['type'] == "condition"}
        190 

    ~/postdoc/src/cytoflow/cytoflow/experiment.py in <dictcomp>(.0)
        187         """Getter for the `conditions` property"""
        188         return {x : pd.Series(self.data[x].unique()).sort_values() for x in self.data
    --> 189                 if self.metadata[x]['type'] == "condition"}
        190 
        191     def subset(self, conditions, values):

    /usr/lib/python3.6/site-packages/pandas/core/series.py in sort_values(self, axis, ascending, inplace, kind, na_position)
       1856         sortedIdx = np.empty(len(self), dtype=np.int32)
       1857 
    -> 1858         bad = isna(arr)
       1859 
       1860         good = ~bad

    /usr/lib/python3.6/site-packages/pandas/core/dtypes/missing.py in isna(obj)
         43     pandas.isnull: alias of isna
         44     """
    ---> 45     return _isna(obj)
         46 
         47 

    /usr/lib/python3.6/site-packages/pandas/core/dtypes/missing.py in _isna_new(obj)
         60         return obj._constructor(obj._data.isna(func=isna))
         61     elif isinstance(obj, list) or hasattr(obj, '__array__'):
    ---> 62         return _isna_ndarraylike(np.asarray(obj))
         63     else:
         64         return obj is None

    /usr/lib/python3.6/site-packages/numpy/core/numeric.py in asarray(a, dtype, order)
        529 
        530     """
    --> 531     return array(a, dtype, copy=False, order=order)
        532 
        533 

    /usr/lib/python3.6/site-packages/pandas/core/categorical.py in __array__(self, dtype)
       1206             categorical.categories.dtype
       1207         """
    -> 1208         ret = take_1d(self.categories.values, self._codes)
       1209         if dtype and not is_dtype_equal(dtype, self.categories.dtype):
       1210             return np.asarray(ret, dtype)

    /usr/lib/python3.6/site-packages/pandas/core/algorithms.py in take_nd(arr, indexer, axis, out, fill_value, mask_info, allow_fill)
       1381     func = _get_take_nd_function(arr.ndim, arr.dtype, out.dtype, axis=axis,
       1382                                  mask_info=mask_info)
    -> 1383     func(arr, indexer, out, fill_value)
       1384 
       1385     if flip_order:

    pandas/_libs/algos_take_helper.pxi in pandas._libs.algos.take_1d_float64_float64()

    /usr/lib/python3.6/site-packages/pandas/_libs/algos.cpython-36m-x86_64-linux-gnu.so in View.MemoryView.memoryview_cwrapper()

    /usr/lib/python3.6/site-packages/pandas/_libs/algos.cpython-36m-x86_64-linux-gnu.so in View.MemoryView.memoryview.__cinit__()

    ValueError: buffer source array is read-only

I found this error on the pandas issue tracker, but it seemed to pop up in a different context. My workaround was to edit [``experiment.py:188``](https://github.com/bpteague/cytoflow/blob/e1dbbdc4d4a920a738689362f3793e4492e11102/cytoflow/experiment.py#L188), copying the argument to ``pd.Series``:

            return {x : pd.Series(self.data[x].unique().copy()).sort_values() for x in self.data
                                                       ^^^^^^^

I'm using Python 3.6, this came up with both pandas-0.20.3 and pandas-0.21.0.

**Comment by bpteague** [comment]
Huh.  Okay.  I can't reproduce it, but that looks like a pretty innocuous addition.  I'll include it in the 1.0 release (coming out Real Soon Now.)  Thanks!
