### ISSUE TITLE
Logicle: can't scale arbitrary matplotlib graphs

### ISSUE THREAD

**Issue by ron-weiss** [bpteague/cytoflow#17]

**Comment by bpteague** [comment]
Repro: make a 1D Stats view, then plt.xscale("logicle").

**Comment by ron-weiss** [comment]
Thanks!

________________________________

**Comment by bpteague** [comment]
This is actually the intended behavior. The "logicle" scale needs to be parameterized with some actual data -- you have to call utility.scale.scale_factory() to get the scaling function.

That seems unfriendly, so I've added "scale" or "{x,y}scale} parameters to the 1d stats, 2d stats and bar chart views.
