### ISSUE TITLE
Table not populating in 0.80 for relatively trivial experiment

### ISSUE THREAD

**Issue by NicholasDeLateur** [bpteague/cytoflow#177]
### DESCRIPTION:
A table cannot be formed, and thus not exported, of 5 plasmids and their Geometric Mean red channel. 

This workflow works in 0.52, but not 0.80

[180319_CytoFlow080_tableviewbug.log](https://github.com/bpteague/cytoflow/files/1825795/180319_CytoFlow080_tableviewbug.log)

Github doesn't support .flv or .fcs, go here to find them: https://www.dropbox.com/sh/oq9ds3wkf481x4t/AAAhaRgarXPK0pvJKsflDH-ia?dl=0

**Comment by bpteague** [comment]
@NicholasDeLateur  thanks for the bug report!  Unfortunately, your screencast didn't capture the experimental setup window.  Could you take a quick screenshot of it?

**Comment by NicholasDeLateur** [comment]
Added to the dropbox folder.

**Comment by bpteague** [comment]
I can't find it.  I suppose it's possible it hasn't updated yet...

**Comment by NicholasDeLateur** [comment]
ExperimentalSetup.PNG

**Comment by bpteague** [comment]
Fixed by 2ade198d8451fd89cd7622b6ff5a586a532a0bce and 3c4ffedfb97daca02232d725910d7be34e4aa0d0
