### ISSUE TITLE
Conda process error when installing to the Anaconda Navigator dashboard

### ISSUE THREAD

**Issue by NicholasDeLateur** [bpteague/cytoflow#179]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
Using Anaconda 1.6; Trying to install gave the following error:
PackagesNotFoundError: The following packages are not available from current channels:

- cytoflow==untagged

Current channels:

- https://conda.anaconda.org/bpteague/win-64
- https://conda.anaconda.org/bpteague/noarch
- https://repo.continuum.io/pkgs/main/win-64
- https://repo.continuum.io/pkgs/main/noarch
- https://repo.continuum.io/pkgs/free/win-64
- https://repo.continuum.io/pkgs/free/noarch
- https://repo.continuum.io/pkgs/r/win-64
- https://repo.continuum.io/pkgs/r/noarch
- https://repo.continuum.io/pkgs/pro/win-64
- https://repo.continuum.io/pkgs/pro/noarch
- https://repo.continuum.io/pkgs/msys2/win-64
- https://repo.continuum.io/pkgs/msys2/noarch

**Comment by bpteague** [comment]
yeah, this isn't going to work until i finish actually releasing the release.  hopefully this afternoon...
