### ISSUE TITLE
BioCEL error: "same voltages"

### ISSUE THREAD

**Issue by cvduffy29** [bpteague/cytoflow#19]
When I try to follow the "small molecule induction curve with yeast" example using the data from BioCEL, I get the error "CytoflowError: Tube G2-Y_LitR-1_0uM_DOX_P3_015.fcs doesn't have the same voltages" when I enter the following:

> inputs = {
>     "G2-Y_LitR-0_01uM_DOX_P3_011.fcs" : 0.01,
>     "G2-Y_LitR-0_10uM_DOX_P3_012.fcs" : 0.10,
>     "G2-Y_LitR-0_50uM_DOX_P3_013.fcs" : 0.50,
>     "G2-Y_LitR-0_75uM_DOX_P3_014.fcs" : 0.75,
>     "G2-Y_LitR-0uM_DOX_P3_010.fcs" : 0,
>     "G2-Y_LitR-1_0uM_DOX_P3_015.fcs" : 1.0,
> }
> 
> tubes = []
> for filename, dox in inputs.iteritems():
>     tubes.append(flow.Tube(file = filename, conditions = {'DOX' : dox}))
>     
> ex = flow.ImportOp(conditions = {'DOX' : "log"}, tubes = tubes).apply()

**Comment by bpteague** [comment]
If Deepak didn't collect the tubes with the same voltages, then I can't help you.  If you're still desperate to load the data, append "ignore_v = True" to the ImportOp constructor's parameters -- but this BREAKS a lot of the assumptions that the software is built on.
