### ISSUE TITLE
Will not show diagnostic plot when too many peaks in Pacific Blue-A

### ISSUE THREAD

**Issue by NicholasDeLateur** [bpteague/cytoflow#192]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
I was trying to do a bead calibration
I add the Pacific Blue-A channel and set it to MEBFP
I hit Estimate!
It says "(None, 'Found too many peaks for channel Pacific Blue-A; check the diagnostic plot')"
But it will not give me a diagnostic plot
No matter how many times I click Estimate!
[WillNotGive_PacificBlue_DiagnosticPlot_WhileComplainingTooManyPeaks_AndIShouldCheckTheDiagnosticPlot.log](https://github.com/bpteague/cytoflow/files/1998980/WillNotGive_PacificBlue_DiagnosticPlot_WhileComplainingTooManyPeaks_AndIShouldCheckTheDiagnosticPlot.log)

  
**Don't forget to attach the log file to this bug report!**

**Comment by NicholasDeLateur** [comment]
Beads file
[Beads AK02.zip](https://github.com/bpteague/cytoflow/files/1998989/Beads.AK02.zip)

**Comment by NicholasDeLateur** [comment]
I raised peak threshold to 1000 and now it'll show me the diagnostic plots. The Pacific Blue-A looks perfectly normal to me, and it's not clear why the threshold was the problem, since it used to be set at the default 100 and the noise region on the left doesn't reach that. I thought maybe if that noisy region on the left was hitting the threshold that might explain it, but it doesn't seem like that's it....
![](https://puu.sh/AlEYC/af4d4fc266.png)

**Comment by NicholasDeLateur** [comment]
No, wait, that Peak Threshold can't be the Y-axis on the diagnostic graphs because they only go up to 400 and the threshold is now 1000 so it doesn't mean what I think it means.

**Comment by NicholasDeLateur** [comment]
Raising Peak Threshold to even just 200 still solves the problem. 
Still fails to show a diagnostic plot at 100. 

I (now) realize that it was a problem on my end not to raise the Peak Threshold, but I assume it's still a problem, maybe minor rather than major, to not show a diagnostic plot even when the thresholds aren't set well, much more when you tell me to look at a diagnostic plot!

**Comment by bpteague** [comment]
fixed in HEAD
