### ISSUE TITLE
Saving Jupyter Notebook doesn't automatically give a file extension

### ISSUE THREAD

**Issue by NicholasDeLateur** [bpteague/cytoflow#193]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
I exported to Jupyter Notebook. When prompted I gave a file name, and it had autoselected the bottom bar in the Windows Explorer screen to be .ipynb, but when I saved the file it did not give that file extension type and it was just a "FILE" to windows until I manually added it. 

It knows to do this with CSV, although I'm not sure it always did when I think back to it. 

It'd be nice but obviously minor. 
  
**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment]
known issue (see #185 ).  Fixed in HEAD, and will be included in the next release.
