### ISSUE TITLE
No median statistic

### ISSUE THREAD

**Issue by NicholasDeLateur** [bpteague/cytoflow#196]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
I know many people wouldn't approve of using Median to describe populations on a log scale, but the lab downstairs publishes multiple science papers with this method and I'd like to be able to check my data via this method and see how close/far or legit/illegit the data it puts out is compared to geometric mean. 

**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment]
seriously?  i didn't include median as an available function?  for shame.

**Comment by bpteague** [comment]
fixed in HEAD.
