### ISSUE TITLE
Drastically increasing DPI while exporting a png is pretty catastrophic

### ISSUE THREAD

**Issue by NicholasDeLateur** [bpteague/cytoflow#199]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
I made a 2D line graph
I clicked save plot
I changed default DPI value from 96 to 4096 and tried to export as .png
I didn't choose this value randomly, it's the DPI I use when I save figs as .png when using matplotlib to get them still looking crisp when embedded in .ppt. But it seems that only 96 DPI is much better looking for cytoflow pngs than matplotlib pngs? I'm sure that doesn't make sense but that's my experience right now. 

It then gave the following errors and wouldn't let me do anything else. 
[DPI_bugreport_workflow.zip](https://github.com/bpteague/cytoflow/files/2073452/DPI_bugreport_workflow.zip)
![ss 2018-06-05 at 01 51 04](https://user-images.githubusercontent.com/15463085/40993829-a05ddeee-68c8-11e8-80a4-3dd9100cfd47.png)
![ss 2018-06-05 at 01 50 44](https://user-images.githubusercontent.com/15463085/40993830-a06fb498-68c8-11e8-8921-41039da9c484.png)

**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment]
congratulations! you crashed the back-end process!  thanks for the bug report, i'll have a look.

**Comment by bpteague** [comment]
looks like you've run into this bug in matplotlib: https://github.com/matplotlib/matplotlib/issues/6572

perhaps this afternoon i'll try updating the version of matplotlib i'm using.  it's a little involved, unfortunately.

**Comment by bpteague** [comment]
matplotlib's output is limited to 65535 pixels in each dimension (for raster outputs) and the image must have fewer than 2**30 pixels total.  you were fine on the first one, but not the second. i've added a check for dimensions that are too big.

and of course, the real answer for high-quality graphics is to use a vector format like PDF or SVG.

thanks for the report!  fixed in HEAD.
