### ISSUE TITLE
Copy FCS importer out of Gore lab flow tools to reduce dependencies

### ISSUE THREAD

**Issue by bpteague** [bpteague/cytoflow#2]

**Comment by eyurtsev** [comment]
I'm going to make it available as a separate package. Probably within ~2 weeks time.

**Comment by eyurtsev** [comment]
Source code: https://github.com/eyurtsev/fcsparser Or you can get it from pip (pip install fcsparser). Should have minimal dependencies.

**Comment by bpteague** [comment]
Done.  Thanks, Eugene!
