### ISSUE TITLE
Can't remove tubes

### ISSUE THREAD

**Issue by NicholasDeLateur** [bpteague/cytoflow#200]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
I analyzed a bunch of samples with a workflow
I want to apply the same workflow to a new set of samples
I open the .flow
I open the experiment dialog
I add all the new tubes
I try to delete all the old tubes
It gives me an error message. 

Is there a different SOP for applying a .flow to a new set of tube? 
 
![ss 2018-06-05 at 03 28 29](https://user-images.githubusercontent.com/15463085/40998283-55f4f43e-68d5-11e8-854b-001e65072cf9.png)

[pL2f1517.zip](https://github.com/bpteague/cytoflow/files/2073707/pL2f1517.zip)

**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment]
pretty sure this is fixed in the new import dialog.  if not, please re-open.
