### ISSUE TITLE
Error reading metadata on a particular sample

### ISSUE THREAD

**Issue by NicholasDeLateur** [bpteague/cytoflow#201]
[Beep.log](https://github.com/bpteague/cytoflow/files/2124960/Beep.log)
[beep.zip](https://github.com/bpteague/cytoflow/files/2124962/beep.zip)

### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
I attempted to upload what should be completely vanilla 24 samples
Cytoflow rejects the samples with the following error:
FCS reader threw an error reading metadata for tube Z:/home/delateur/Experiments/QSFT/180611 - QSFT Characterization 1/Raw Data/13062018/180613 QSTF Screen/Plate1/180613 QSTF Screen_Specimen_001_B1_B01_006.fcs

When I removed tube B1 it allowed the tubes to be imported. 

All samples were attained with the HTS in the exact same fashion so I absolutely cannot think of why that tube would be different. 
  
I have attached the log file and all the tubes.

**Comment by NicholasDeLateur** [comment]
Update:
After deleting the sample from the import and then reopening the sample import dialogue and readding it it worked perfectly and without complaint.

**Comment by NicholasDeLateur** [comment]
This was on Cytoflow 0.9.3

**Comment by bpteague** [comment]
they load fine for me on HEAD.  there used to be a bug where the import operation would "remember" some stuff across invocations.  that bug has definitely been squashed.  if you run into it again (esp if you come up with a good reproduction), please re-open.
