### ISSUE TITLE
Plot title with multiple plots via vertical panes not acting as expected

### ISSUE THREAD

**Issue by NicholasDeLateur** [bpteague/cytoflow#202]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
When I added a title to my plot it (1) did not add it to the top of the entire figure, but rather only to the top of the most bottom verticle pane and (2) overwrote the parameter (Plasmid = N). Please see attached screenshots. 
 
![withouttitle](https://user-images.githubusercontent.com/15463085/41749501-b321dfc6-7584-11e8-8961-3e3316b35ef6.png)

![withtitle](https://user-images.githubusercontent.com/15463085/41749505-b73f5bba-7584-11e8-8a7a-71fa24b63285.png)

[Las_And_Rhl_bugreport.zip](https://github.com/bpteague/cytoflow/files/2125601/Las_And_Rhl_bugreport.zip)

**Don't forget to attach the log file to this bug report!**

**Comment by NicholasDeLateur** [comment]
This is with Cytoflow 0.9.3

**Comment by bpteague** [comment]
thanks for the report, this has been bugging me for a while but i kept forgetting.
this should be fixed in HEAD.
