### ISSUE TITLE
CSV export not writing correctly

### ISSUE THREAD

**Issue by NicholasDeLateur** [bpteague/cytoflow#203]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
When exporting multi dimensional data sets with sub-columns, it does not write the correct column heads
I expect a column to be Plasmid = pL2f1555, subcoumn to be rhlAHL_nM = 0
I get a column to be Plasmid = pL2f1555, subcoumn to be rhlAHL_nM = pL2f1555
Critical/Major in that it destroys the information and the only way to get it back is to try to refer back to the experiment and see if you can find the induction trends and such. 
[CSV_export_improper.zip](https://github.com/bpteague/cytoflow/files/2138521/CSV_export_improper.zip)

  
**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment]
fixed in HEAD.  thanks for the report.
