### ISSUE TITLE
FCS data transform

### ISSUE THREAD

**Issue by HectorM14** [bpteague/cytoflow#210]
I find that my loaded .FCS data is missing a transform to more closely match how it appears in the original FC software. The [transform.to_rfi](https://taborlab.github.io/FlowCal/reference/FlowCal.transform.html#FlowCal.transform.to_rfi) in FlowCal seems to do the trick. Is this a step that is supposed to happen automatically in cytoflow when reading my file, or can this step be added to the processing pipeline?
The file is FCS 2.0
Thanks for the great tool!

**Comment by bpteague** [comment]
Hi @HectorM14 -- thanks for the bug report.  I recently implemented this functionality (ie, the Import operation re-scales data recorded with a log amplifier to a linear scale) and hope to release a new version in the next few days.

I'm going to close this bug for now.  If the new version doesn't do what you expect, please re-open the bug and attach (a) the FCS file, and (b) a screen shot of the original software showing how you expect it to look.  Thanks!

**Comment by HectorM14** [comment]
Great, looking forward to it!
