### ISSUE TITLE
Sphereotech new Master Lot AK02 not in GUI

### ISSUE THREAD

**Issue by NicholasDeLateur** [bpteague/cytoflow#219]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
Can you please add the new Master Lot for 8-peak Sphereotech beads to the GUI dropdown? It is AK02, and up to 12% or more different values for various channel numbers for various colors to it's close counterpart AE01. 
  
**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment]
done
