### ISSUE TITLE
Imported tubes do not have useful condition columns

### ISSUE THREAD

**Issue by jeremygam** [bpteague/cytoflow#224]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
  - What were you trying to do? Import tubes taken on an Attune Flow Cytometer using Cytoflow GUI
  - What happened? The only auto-generated columns for tubes are $SRC and $SMNO, which are all 'NA' and 'Group' for every sample. This means that we cannot identify which samples are which
  - What did you expect to happen? Auto-generated columns would identify which tubes are which uniquely. For the FCS files we are using, this could be $FIL or even the file name itself followed by .fcs
  
Uploaded two example fcs files here (they are renamed to .txt so that they can be uploaded to Github directly on this message - renaming to .fcs after downloading should hopefully work)

**Don't forget to attach the log file to this bug report!** 

<img width="1378" alt="screen shot 2018-11-07 at 10 43 00 am" src="https://user-images.githubusercontent.com/27288464/48141991-effc2700-e279-11e8-8606-c2af2789398a.png">
[2018-11-02_Group_Sample(1).txt](https://github.com/bpteague/cytoflow/files/2558061/2018-11-02_Group_Sample.1.txt)
[2018-11-02_Group_Sample(2).txt](https://github.com/bpteague/cytoflow/files/2558062/2018-11-02_Group_Sample.2.txt)

**Comment by bpteague** [comment]
Thanks!  This is fixed in 1.0 -- with the new experiment setup dialog, you can choose to use columns from any of the FCS metadata.  Hoping to release a beta by Jan 1.

**Comment by bpteague** [comment]
(also, I don't have ready access to an Attune -- if this is still an issue in the new release, please re-open, then get in touch with some example data?)
