### ISSUE TITLE
Pip Install Version is very old (0.8)

### ISSUE THREAD

**Issue by mcrone** [bpteague/cytoflow#225]
### PLATFORM (Mac, PC, Linux, other):
Mac

### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
MacOS 10.14.1

### SEVERITY (Critical? Major? Minor? Enhancement?):
Minor

### DESCRIPTION:
  - What were you trying to do?

I was trying to use pip to install the latest version of cytoflow.

  - What happened?

It installed version 0.8 which relies on many old packages that I don't want to use (like matplotlib 1.5)

  - What did you expect to happen?

I expected it to install the latest version.
  
**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment]
Sorry that PyPI wheels fell off the radar for recent releases.  Mac and Windows wheels and source are uploaded for v1.0.
