### ISSUE TITLE
how to make plots larger

### ISSUE THREAD

**Issue by kkiwimagi** [bpteague/cytoflow#229]
### Thank you for your bug report!  

Please fill out the following template.

### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
 OSX 12 Windows 10
### SEVERITY (Critical? Major? Minor? Enhancement?):
Major

### DESCRIPTION:
  - What were you trying to do? make bleed though and other plots larger
As they are now I can not read them if I have 4 colors. Is there a way to make them larger?

  - What happened? Small hard to read images

  - What did you expect to happen? Automated sizing of image that scales with size of plot. Though perhaps this is only possible with a save option that does not resize based on plot space of notebook.
Wonder if it would be possible to add fit value for lines accessible inside the bleed through object. Though then other plots types would also need this access (access to fit lines values of color and bead plots). Maybe it would be possible to have option to make plots individual instead of inside a subplot... That way is wold be easier to scale them by the the pyplot.gcf() handle, perhaps a more generalizable fix. Just ideas

Thank you again,
K
  
**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment]
Hi Katherine - I've updated this code somewhat -- in particular, I've shifted the annotations and they should scale better.  However, I don't have any four-color data to test with.  If you try it in 1.0 (releasing Real Soon Now) and it's still a problem, please re-open.

Also, you *can* access the spillover matrix, both in the operation (after calling `estimate()`) and in the metadata of the `Experiment` produced by calling `apply()`.  In the future, please use separate Github issues to report distinct bugs or feature requests (:
