### ISSUE TITLE
Updating cytoflow Anaconda package to be compatible with Seaborn version 0.11

### ISSUE THREAD

**Issue by jaipadmakumar** [bpteague/cytoflow#281]
### Thank you for your bug report!  

Please fill out the following template.

### PLATFORM (Mac, PC, Linux, other):
Mac
### SEVERITY (Critical? Major? Minor? Enhancement?):
Enhancement
### DESCRIPTION:

I've noticed the current cytoflow package available through Anaconda doesn't seem to be compatible with the newest version of Seaborn, which provides some pretty handy visualization tools. It would be great to have this updated so we can update seaborn through Conda.

**Comment by bpteague** [comment]
Thanks for the report. I've got an active branch that updates all the dependencies to their current versions (see branch update_depends), but there were a few bugs introduced that I've only recently gotten sorted. Also it's been a tough semester! I should have a new release rolled in the next few weeks.
