### ISSUE TITLE
Updated Cytoflow release?

### ISSUE THREAD

**Issue by Jsakkos** [bpteague/cytoflow#294]
### Thank you for your bug report!  

Please fill out the following template.

### PLATFORM (Mac, PC, Linux, other):
PC
### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
Windows 10
### SEVERITY (Critical? Major? Minor? Enhancement?):
Enhancement
### DESCRIPTION:
The current Cytoflow release, 1.0, is more than two years old. It has a Seaborn 0.9 dependency that is missing new functionality, e.g. log scale on FacetGrids. Will there be a new Conda release anytime soon to match the developer version?
  
**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment]
I'm working on it! Unfortunately, it has not been smooth -- and it hasn't helped that my CI provider, Travis, essentially shut down its "free/open source" tier in December.  Maybe this weekend?

**Comment by bpteague** [comment]
I am heartened by the fact that people are using the project -- that's good motivation for me to keep working on it. But I'm an assistant professor with a heavy teaching load, and COVID has made everything all that much worse. As such, Cytoflow is simply not a terribly high priority -- not when there are courses to prep and quizzes to grade and lectures to record .... but thanks for the bump. Seriously.

**Comment by Jsakkos** [comment]
Thanks for the quick response! I've found Cytoflow to be very useful. I primarily use it in Jupyter notebooks and not the GUI version, but it's nice to have both. I understand that things are tough right now and I appreciate your efforts.
