### ISSUE TITLE
Axis min/max

### ISSUE THREAD

**Issue by har-wradim** [bpteague/cytoflow#61]
Axis ranges as shown in scatter plots or gate view are seemingly calculated incorrectly. This covers all three currently functioning transformations: linear, log and logicle.

E.g. for tests/data/tasbe/beads.fcs this cuts out a small group of events with high FSC and SSC. Compare:

![beads_cytoflow](https://cloud.githubusercontent.com/assets/2794008/23397951/3ff4c09a-fda3-11e6-95e4-fca8010e0e89.png)
![beads_ggcyto](https://cloud.githubusercontent.com/assets/2794008/23397952/3ff95d6c-fda3-11e6-9754-d0d4d8a7fce0.png)

Ubuntu 16.04 x86_64

PACKAGE VERSIONS: ['fcsparser 0.1.2', 'python 2.7.12 (default, Nov 19 2016, 06:48:10) \n[GCC 5.4.0 20160609]', 'matplotlib 1.5.3', 'traits 4.6.0', 'scipy 0.18.1', 'numexpr 2.4.6', 'bottleneck 1.0.0', 'envisage 4.6.0', 'pyface 5.1.0', 'seaborn 0.7.1', 'scikit-learn 0.18.1', 'traitsui 5.1.0', 'cytoflow 0.4.1', 'numpy 1.12.0', 'pandas 0.19.2']

**Comment by har-wradim** [comment]
@bpteague 

The clipping of the axes is done based on hard-coded quantiles in cytoflow/views/*.py:

        min_quantile = kwargs.pop("min_quantile", 0.001)
        max_quantile = kwargs.pop("max_quantile", 0.999)

I think it is highly desirable to make these values adjustable by the user of the API and GUI, because in many applications interesting events are simultaneously rare and show extreme values.

**Comment by bpteague** [comment]
@har-wradim  - yep, this is something I'm still struggling with.  There are instances where seeing rare/extreme events is useful, and instances where those extreme events really screw up the axes.

I'm very close to rolling out release 0.5; one of the major features for the next release is GUI control over more of the plotting parameters, including min and max_quantile.  The fact that they're pulled from kwargs is in preparation for this.

In the meantime, I see more aberrant behavior with minimum values (ie values very close to 0 screwing up a log-scaled axis); maybe I'll try setting max_quantile's default to 1.0 and leaving min_quantile at 0.001.

Thoughts?

**Comment by bpteague** [comment]
PS - one of the driving principles behind Cytoflow is "sane defaults".  Most places, it's obvious what's sane; and in some, it's really not.

**Comment by har-wradim** [comment]
I actually set min_quantile to 0 (and max_quantile to 1) in my instance, but 0.001 may be a reasonable default. I'm looking forward to seeing the solution with user-adjustable limits in the upcoming release.

**Comment by bpteague** [comment]
Sorry if I wasn't clear.  The immediately impending release, 0.5, won't have these parameters adjustable (through the GUI.)  That's on the planning board for 0.6.  (-:

**Comment by bpteague** [comment]
The GUI and module API both will let you set these quantiles now.  If you're still having issues with v1.0 (releasing Real Soon Now), please re-open.  And thanks for the feedback.
