### ISSUE TITLE
Gate preview bug in GUI

### ISSUE THREAD

**Issue by har-wradim** [bpteague/cytoflow#65]
When creating a new gate the middle panel remains blank after providing the gate name and choosing the channels. Only resizing the panel triggers rendering of the plot:

![cytoflow](https://cloud.githubusercontent.com/assets/2794008/23406115/0f59ec76-fdc6-11e6-8a9e-eb29a48ecf73.gif)

If you start drawing when the plot is not rendered, the following exception appears and further work with the current gate becomes impossible:

	Error: AttributeError: draw_artist can only be used after an initial draw which caches the render

	Location:   File "/home/har-wradim/.local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2334, in draw_artist
		raise AttributeError(msg)
	Thread: canvas listen

Also notice that the time required for rendering each time the middle panel is resized, is quite considerable. When the number of the events is high enough (~50000) every resizing results in seconds of delay.

Ubuntu 16.04 x86_64

PACKAGE VERSIONS: ['fcsparser 0.1.2', 'python 2.7.12 (default, Nov 19 2016, 06:48:10) \n[GCC 5.4.0 20160609]', 'matplotlib 1.5.3', 'traits 4.6.0', 'scipy 0.18.1', 'numexpr 2.4.6', 'bottleneck 1.0.0', 'envisage 4.6.0', 'pyface 5.1.0', 'seaborn 0.7.1', 'scikit-learn 0.18.1', 'traitsui 5.1.0', 'cytoflow 0.4.1', 'numpy 1.12.0', 'pandas 0.19.2']

**Comment by bpteague** [comment]
Yep, there were some concurrency bugs in 0.4.1, and this looks like one of them.  I *think* these are all fixed in HEAD.  PS - thanks for the screencast GIF.  (-:

**Comment by har-wradim** [comment]
Great!
