### ISSUE TITLE
2D Stats Bug

### ISSUE THREAD

**Issue by mollyBioCEL20129** [bpteague/cytoflow#73]
Hi Brian! Thank you for making Cytoflow available. We've begun using it in BioCEL and it is extremely helpful. During the course of lab today, we discovered a bug while using the 2D stat plot feature. We found that if the "Group By" categories were selected in a different order in the channel statistics, an error "x statistic and y statistic must have the same indices: [u'DOX',u'TransfectionBins']" was thrown. We were able to resolve this by re-selecting the groupings, however several students ran into this error, so it may be helpful to fix this, such that the 2D stat will work regardless of the order of selection. Thanks!
-Ron's Minions

**Comment by bpteague** [comment]
Dear Molly & Minions -
Thank you for the bug report.  The instructions to reproduce it led me right to the bug, which is fixed in the latest alpha.  This would have taken me forever to find otherwise.
