### ISSUE TITLE
1D Gassian Mixture throws exception

### ISSUE THREAD

**Issue by blakeelias** [bpteague/cytoflow#85]
Steps to reproduce:

0. Download and extract "fcs-data-and-cytoflow-file.zip" (attached).
1. On Mac OS X 10.10.5, open attached .flow file in Cytoflow 0.4.1 (depends on .fcs files also attached)
2. Under "Transfected" 1D Gaussian Mixture, click "Estimate!".
3. I receive the following error box from Cytoflow:

"An exception has occurred.  Please report a problem from the Help menu!

Afterwards, may need to restart Cytoflow to continue working.

Remote process exited with -11"

A Mac OS X crash window also appears, with an option to submit a crash report to Apple. 

[fcs-data-and-cytoflow-file.zip](https://github.com/bpteague/cytoflow/files/910920/fcs-data-and-cytoflow-file.zip)

**Comment by bpteague** [comment]
Hrm.  I'll have a look.  Does it crash with the latest alpha?

**Comment by bpteague** [comment]
I can no longer open this file with latest version of Cytoflow -- it uses the bad old pickling serialization code, not the nice new YAML-based stuff.  Also you're no longer working with Deepak (-;  The newest version is a lot less crashy, and I seem to be able to use a 1D GMM to separate out the two populations -- if it's still an issue, please re-open.
