### ISSUE TITLE
Can't find ChannelStatisticOp

### ISSUE THREAD

**Issue by kkiwimagi** [bpteague/cytoflow#86]
When running the TASBE Workflow for input 18 I run into the following error: 
AttributeError: 'module' object has no attribute 'ChannelStatisticOp'

**Comment by bpteague** [comment]
The new statistics operations are in HEAD but not yet released.  I updated the example notebooks but haven't yet managed to spin the new release -- there are two bugs left to fix before I do so.  Hopefully here in the next few days!  (Though I've been saying that since, oh, the end of January.)
