### ISSUE TITLE
Can't find module geom_sd

### ISSUE THREAD

**Issue by kkiwimagi** [bpteague/cytoflow#87]
Confused on why I can call function flow.geom_mean() but cannot call function flow.geom_sd()
AttributeError                            Traceback (most recent call last)
<ipython-input-33-361e9044d2be> in <module>()
     11                                (dataStruct['Morpho2']==True)]['PE-Tx-Red-YG-A']
     12     print(sampleName, flow.geom_mean(RedData))
---> 13     flow.geom_sd(RedData)

AttributeError: 'module' object has no attribute 'geom_sd'

**Comment by bpteague** [comment]
Similarly, this isn't in version 0.4.1.
