### ISSUE TITLE
treatment of negative values in geom_sd

### ISSUE THREAD

**Issue by kkiwimagi** [bpteague/cytoflow#88]
I am wondering if it would be better to use cmath to calculate the log dealing with the negative number a bit differently. This will allow for imaginary numbers that will be squared (and therefore reconciled) in the np.std.
def geom_sd(a):
    a = np.array(a)
    u = flow.geom_mean(a)
    a[a <= 0] = np.abs(a[a <= 0]) + 2 * u
    
    return np.exp(np.std(np.log(a)))

(possible update)
import cmath as cm
def geom_sd(a):
    a = np.array(a)
    u = flow.geom_mean(a)
    return np.exp(np.std([cm.log(x) for x in a]))

**Comment by bpteague** [comment]
Hrm. I'll need to give this some thought.  The current approach doesn't discard the negative numbers, it flips them to the other side of the geometric mean.  Thanks for the proposal!

**Comment by kkiwimagi** [comment]
Wondering if it is still a geometric mean if you flip the values to the other side, as the assumed distribution is not symmetrical about the mean, just a thought. Hope it is helpful.

**Comment by bpteague** [comment]
Have a look at the following reference, he validates this approach pretty rigorously:
```
Geometric mean for negative and zero values
Elsayed A. E. Habib
International Journal of Research and Reviews in Applied Sciences  11:419 (2012)
http://www.arpapress.com/Volumes/Vol11Issue3/IJRRAS_11_3_08.pdf
```
